# Generated by Django 4.1.4 on 2022-12-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(choices=[('nasdaq100', 'NASDAQ 100'), ('tesla', 'Tesla'), ('google', 'Google'), ('apple', 'Apple'), ('amazon', 'Amazon'), ('btc', 'Bitcoin'), ('gold', 'Gold'), ('oil', 'Oil')], max_length=50)),
                ('close_price', models.FloatField()),
                ('vwap', models.FloatField()),
                ('signal', models.CharField(max_length=50)),
                ('accuracy', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
