# Generated by Django 4.1.4 on 2023-05-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='conversation_id',
            field=models.CharField(default='87781cab-c075-4ac4-b72e-768c66b81802', max_length=100, unique=True),
        ),
    ]
