# Generated by Django 4.1.4 on 2023-05-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_chathistory_conversation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='conversation_id',
            field=models.CharField(default='bff7e3c4-2b57-44bf-b2ef-2d915e690894', max_length=100, unique=True),
        ),
    ]
