# Generated by Django 4.1.4 on 2023-05-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_chathistory_conversation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='conversation_id',
            field=models.CharField(default='97be56ac-7bf6-4a9f-a18e-f4f4292c112e', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_comments_group', to='myapp.commentgroup'),
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='emoji_reactions',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_emoji_reactions_group', to='myapp.emojireactiongroup'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_comments', to='myapp.comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='emoji_reactions',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_emoji_reactions', to='myapp.emojireaction'),
        ),
    ]
