# Generated by Django 4.1.4 on 2023-05-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_chathistory_conversation_id_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='conversation_id',
            field=models.CharField(default='9f2b37e9-f04e-43fc-850a-c16743c94beb', max_length=100, unique=True),
        ),
    ]
