# Generated by Django 4.1.4 on 2023-05-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_chathistory_conversation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='conversation_id',
            field=models.CharField(default='00805cff-46d0-4055-9629-78fdef0da17a', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='emojireaction',
            name='emoji',
            field=models.CharField(choices=[('❤️', '❤️'), ('👍', '👍'), ('👎', '👎'), ('😠', '😠'), ('😊', '😊')], max_length=20),
        ),
    ]
