# Generated by Django 4.1.4 on 2023-05-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_chathistory_conversation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='conversation_id',
            field=models.CharField(default='7a139e91-defa-4988-b536-9ab2b63d1b14', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='emojireaction',
            name='emoji',
            field=models.CharField(choices=[('heart', '❤️'), ('thumbs_up', '👍'), ('thumbs_down', '👎'), ('angry', '😠'), ('smiling_face', '😊')], max_length=20),
        ),
    ]
