# Generated by Django 4.1.4 on 2023-05-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_chathistory_conversation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='conversation_id',
            field=models.CharField(default='1036436e-0784-4f7e-91bb-1a230b02326f', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='emojireaction',
            name='emoji',
            field=models.CharField(choices=[('❤️', 'heart'), ('👍', 'thumbs_up'), ('👎', 'thumbs_down'), ('😠', 'angry'), ('😎', 'cool'), ('😊', 'smile')], max_length=20),
        ),
    ]
