# Generated by Django 4.1.4 on 2023-05-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_chathistory_conversation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='conversation_id',
            field=models.CharField(default='0aa41274-25ba-405a-92b9-4b357d448edf', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='emojireaction',
            name='emoji',
            field=models.CharField(choices=[('❤️', 'heart'), ('👍', 'thumbs_up'), ('👎', 'thumbs_down'), ('😠', 'angry'), ('😊', 'smiling_face')], max_length=20),
        ),
    ]
