# Generated by Django 4.1.4 on 2023-05-18 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_chathistory_conversation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='emoji_reactions',
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='conversation_id',
            field=models.CharField(default='08e8b58b-6e1e-4fdf-a387-e309b5e9eca4', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.post'),
        ),
        migrations.AlterField(
            model_name='emojireaction',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emoji_reactions', to='myapp.post'),
        ),
    ]
