# Generated by Django 4.1.4 on 2023-05-19 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_post_comments_remove_post_emoji_reactions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentgroup',
            old_name='content',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='myapp.comment'),
        ),
        migrations.AddField(
            model_name='post',
            name='emoji_reactions',
            field=models.ManyToManyField(blank=True, related_name='emoji_reactions', to='myapp.emojireaction'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='conversation_id',
            field=models.CharField(default='6bb15b8c-8094-4232-a83c-adfc9c7553c0', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='myapp.post'),
        ),
        migrations.AlterField(
            model_name='emojireaction',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_emoji_reactions', to='myapp.post'),
        ),
    ]
