# Generated by Django 4.1.4 on 2023-05-19 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_content_commentgroup_comment_post_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppost',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='grouppost',
            name='emoji_reactions',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='emoji_reactions',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_live',
        ),
        migrations.AddField(
            model_name='user',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='conversation_id',
            field=models.CharField(default='c28b3ab7-87b9-46a5-bb26-c2a34bba9cf4', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.post'),
        ),
        migrations.AlterField(
            model_name='commentgroup',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_group', to='myapp.grouppost'),
        ),
        migrations.AlterField(
            model_name='emojireaction',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emoji_reactions', to='myapp.post'),
        ),
        migrations.AlterField(
            model_name='emojireactiongroup',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emoji_reactions_group', to='myapp.grouppost'),
        ),
    ]
