# Generated by Django 4.1.4 on 2023-05-20 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0015_remove_grouppost_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='conversation_id',
            field=models.CharField(default='30384b9f-7127-4fef-8b3b-b1db5b96fc79', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='emojireaction',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emojireaction',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='emoji_reactions', to='myapp.post'),
            preserve_default=False,
        ),
    ]
