# Generated by Django 4.1.4 on 2023-05-20 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_chathistory_conversation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentgroup',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_comments', to='myapp.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='conversation_id',
            field=models.CharField(default='40b538d9-785b-48fe-9e2d-3d1eb06ba2af', max_length=100, unique=True),
        ),
    ]
